services:
  preprocessing:
    build:
      context: install/preprocessing
    command: /bin/bash
    restart: unless-stopped
    volumes:
      - ./code/preprocessing:/code
      - ./code/common:/code/common
      - ./data/preprocessing:/data:ro
      - ./results/preprocessing:/results
    working_dir: /code
    environment:
      - DATA_DIR=/data
      - RESULTS_DIR=/results
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]
    stdin_open: true
    tty: true

  webapp:
    build:
      context: install/webapp
    command: bash startserver.sh
    restart: unless-stopped
    expose:
      - "${PORT}"
    volumes:
      - ./code/webapp:/code
      - ./code/common:/code/common
      - ./data/webapp:/data:ro
      - ./logs/webapp:/logs
      - staticnginx:/static
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=0
      - DATA_DIR=/data
      - LOGS_DIR=/logs
      - CUDA_VISIBLE_DEVICES=0
    working_dir: /code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    ports:
      - "${PORT}:${PORT}"
      - "443:443"
    volumes:
      - staticnginx:/var/www/static:ro
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - webapp

volumes:
  staticnginx: