channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - django=5.1
  - django-cors-headers=4.6
  - geopandas=0.14
  - geopy=2.4.1
  - gunicorn=23.0
  - holidays=0.47
  - matplotlib=3.9.3
  - pandas=1.5.3
  - pip=24.3
  - plotly=5.24
  - pymannkendall=1.4
  - python-dotenv=1.0
  - python-kaleido=0.2
  - pytorch=2.5
  - pytorch-cuda=12.1
  - seaborn=0.13
  - scikit-learn=1.2.1
  - torchvision=0.20
  - torchaudio=2.5
